version: "3.8"
services:
### Postgres Database ###
  postgres:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dinu1234
      POSTGRES_DB: db
### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:6.21
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
### API Spring Boot ###
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: dinu1234
    ports:
      - "8080:8080"
